### ISSUE TITLE
Replace `nn.MultiheadAttention` with `class Attention`

### ISSUE THREAD

**Issue by OrangeSodahub** [mlfoundations/open_clip#196]
I want to ask if I replace https://github.com/mlfoundations/open_clip/blob/b4cf9269b0b11c0eea47cb16039369a46bd67449/src/open_clip/model.py#L308 with https://github.com/mlfoundations/open_clip/blob/b4cf9269b0b11c0eea47cb16039369a46bd67449/src/open_clip/model.py#L210 and will it work?

**Comment by rwightman** [comment]
@OrangeSodahub yes, if you do it as per the commented out code blocks https://github.com/mlfoundations/open_clip/blob/b4cf9269b0b11c0eea47cb16039369a46bd67449/src/open_clip/model.py#L301-L327 

it works and should be backwards compatible if none of the extra features are enabled

I had to remove it as a dynamic option because the different type signature for the call was causing torchscript to break, will fix it at some point so it can be enabled properly via config
