### ISSUE TITLE
error when running training/main.py

### ISSUE THREAD

**Issue by nikky4D** [mlfoundations/open_clip#35]
I am getting a ModuleNotFoundError for training when running src/training/main.py. It points to line 19 in main.py, the import function. 

Edit: Fixed it. Forgot to add pythonpath

**Comment by mitchellnw** [comment]
I feel like there's a better solution to this so that you don't have to add that to PYTHONPATH -- anybody know it?

**Comment by ludwigschmidt** [comment]
Could we add it to [sys.path](https://docs.python.org/3/library/sys.html#sys.path) programmatically?

**Comment by rom1504** [comment]
doing a proper python module with __init__.py and setup.py would do the trick

**Comment by mitchellnw** [comment]
Then I will re-open this issue and mark as `good first issue` so that someone can submit a PR with this change.

**Comment by rwightman** [comment]
The latest changes have improved this for `open_clip` model with the modelling and loss code. It can be installed via `python setup.py install` or `pip -e .` from the git checkout, or `pip install open_clip_torch`

The training code is not included in the installed packages though but with the package installed one could run scripts directly from training folder.

For the most part I still run without the package installed directly from the `src/` folder (so that open_clip is accessible by its name) where I do

```
cd open_clip/src
torchrun --nproc_per_node=4 \
    -m training.main \
    --train-data '/data/cc12m/cc12m-train-{0000..2175}.tar' \
    --train-num-samples 10968539 \
    --dataset-type webdataset \
    --batch-size 320 \
    --precision amp \
    --workers 4 \
    --imagenet-val /data/imagenet/validation/``
```
