### ISSUE TITLE
coca follow ups

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#390]
* [x] make B/32 checkpoint compatible with current code
* [x] release L/14 checkpoint
* [x] remove support for non dict mode in train code https://github.com/mlfoundations/open_clip/pull/308#discussion_r1089834375
* [x] add beam search generate https://github.com/mlfoundations/open_clip/pull/341
* [x] add in readme how to generate with a pretrained model
* [ ] Add instructions for captioning eval in readme  https://github.com/LAION-AI/CLIP_benchmark/pull/63
* [x] (Optional) provide a coca fine tuned for captioning on coco
* [x] Release post mentioning training runs, how to train, how to evaluate, results, how to generate 
* [ ] (Optional) past key for speed up

**Comment by rwightman** [comment]
@rom1504 that's not 'remove an option to not output a dict', that was the whole point on the model side so other users of the model don't break, it's 'remove support for non-dict mode in train code'

**Comment by rom1504** [comment]
Alright

**Comment by vturrisi** [comment]
Hey! Thanks for the great effort in making CoCa available.

I was generating captions with CoCa and they work fine with the new beam search implementation. However, I wanted to do top-p/nucleus sampling generation as in BLIP and for that there are a couple of issues with the current implementation. There's no way to enforce minimal number of tokens and the end of sequence token is ignored, so the model will keep generating until the sequence length. I did some quick fixes on my side but since I'm not super familiar with huggingface/openclip that is for sure suboptimal.

I can share more info if needed :)

**Comment by gpucce** [comment]
hi @vturrisi I opened a PR here https://github.com/mlfoundations/open_clip/pull/402 can you try it and see if this is what you expected?

**Comment by rom1504** [comment]
Done. Last point tracked there https://github.com/mlfoundations/open_clip/issues/409

**Comment by lucidrains** [comment]
@gpucce thank you for your amazing work Giovanni!

**Comment by ludwigschmidt** [comment]
Indeed, awesome work here!

**Comment by usuyama** [comment]
Awesome work!

**Comment by alexcode4u** [comment]
@rom1504 Is there way to generate several outputs using top_k/top_p sampling for CoCa? May be there is some parameter like "num_return_sequences" in hugging face? I have not found anything like that in generate function. https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/coca_model.py#L167
