### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by chinmay5** [mlfoundations/open_clip#474]
I am trying to adapt the code for working on a custom medical dataset. Unlike Imagent, I do not have a "zero-shot evaluation." So, I am using only the training split and a VIT B 32 model. I was wondering what the parameter configuration for fine-tuning the model is. I have around 200k image-text pairs, but since these are medical reports, there is not too much diversity in the text. Hence, I want to fine-tune the model embeddings.

As an add-on, how can we modify the code to work with one-channel images? Currently, I just use contents from the `train` folder. Thus the default train transforms are used. Is it possible to change the default train transforms and adapt them to the medical domain?

Thanks in advance.

**Comment by mitchellnw** [comment]
We do not have any official parameter configurations for fine-tuning a CLIP model, but you can do `--model ViT-B-32 --pretrained laion2b_s34b_b79k` to start out with this pre-trained model, for instance. Then I would advise using a very low LR. One issue is that CLIP models like these are hard to fine-tune on image-text pairs without a very large batch size (like that used for pre-training) which requires lots of compute.

Probably the easiest way to deal with one-channel images is to just treat them like three-channel (gray) images. Otherwise you won't be able to use a pre-trained model.

**Comment by chinmay5** [comment]
Thank you so much for the quick response. As a followup 

1. Is it possible to perform custom data augmentation without changing the source code?
2. How do I unfreeze the last few image layers?

Thanks in advance.

**Comment by mitchellnw** [comment]
1. yes, look into this argument https://github.com/mlfoundations/open_clip/blob/main/src/training/params.py#L237
2. yes, look into these arguments https://github.com/mlfoundations/open_clip/blob/main/src/training/params.py#L213-L230

**Comment by chinmay5** [comment]
Thank you so much for your response.
