### ISSUE TITLE
How to open tuned clip with open clip in transformers?

### ISSUE THREAD

**Issue by AlexWortega** [mlfoundations/open_clip#591]
Hi there, i am trying to use tuned open_clip with 
```
from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained('my model')
```
but get a error that model has a different layer names + different configs. I tuned model with tutorial from  your repo https://github.com/mlfoundations/open_clip

**Comment by rwightman** [comment]
OpenCLIP models are not compatible with transformers without converting. The OpenCLIP save to HF hub pushes in OpenCLIP form...

The pure vit + builtin text transformers models can be converted to transformers though, you can push the configs and checkpoint file to same repo as open clip because they don't overlap.

Having this functionality builtin would be good, but limited people power here..

A super hacky script that can be used after tweaking config for your model: https://gist.github.com/rwightman/c79fd0241ed3c860e898114931c07990
